run:
  timeout: 1h0m0s

linters-settings:
  gofmt:
    simplify: true
linters:
  enable:
  - gofmt
  - revive
  - gocyclo
  - misspell
issues:
  exclude-use-default: false
linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 1.0
