run:
  timeout: 1h0m0s
linters:
  enable:
  - gofmt
  - golint
  - gocyclo
  - misspell
  disable:
  - staticcheck
issues:
  exclude-use-default: false
linters-settings:
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 1.0
