run:
  timeout: 1h0m0s
linters:
  enable:
  - gofmt
  - revive
  - gocyclo
  - misspell

issues:
  exclude:
    - Error return value of
    - File is not `gofmt`-ed with `-s`
    - File is not `goimports`-ed
linters-settings:
  revive:
    severity: error

  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: True
