apiVersion: v1
kind: Service
metadata:
  name: cicd-webhook
  namespace: cicd-system
  labels:
    cicd.tmax.io/part-of: webhook
spec:
  selector:
    cicd.tmax.io/part-of: webhook
  ports:
    - name: webhook
      port: 24335
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: cicd-system
  labels:
    control-plane: controller-manager
    cicd.tmax.io/part-of: webhook
spec:
  selector:
    matchLabels:
      cicd.tmax.io/part-of: webhook
  replicas: 1
  template:
    metadata:
      labels:
        cicd.tmax.io/part-of: webhook
    spec:
      serviceAccountName: cicd-service-account
      containers:
        - command:
            - /webhook
          image: docker.io/tmaxcloudck/cicd-webhook:latest
          imagePullPolicy: Always
          name: manager
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /logs
              name: operator-log
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: operator-log
          hostPath:
            path: /var/log/cicd-operator/logs
      terminationGracePeriodSeconds: 10
