apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-manager-role
subjects:
- kind: ServiceAccount
  name: cicd-service-account
  namespace: cicd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-manager-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd-manager-role
subjects:
- kind: ServiceAccount
  name: cicd-service-account
  namespace: cicd-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-manager-rolebinding
  namespace: cicd-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd-manager-role
subjects:
- kind: ServiceAccount
  name: cicd-service-account
  namespace: cicd-system
