apiVersion: v1
kind: Secret
metadata:
  name: git-token-secret-name
stringData:
  token-secret-key: xxxxxxxx
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: hello-world
spec:
  git:
    type: gitlab
    apiUrl: http://my.gitlab
    repository: user01/repo01
    token:
      valueFrom:
        secretKeyRef:
          name: git-token-secret-name
          key: token-secret-key
  jobs:
    preSubmit:
      - name: pr-echo
        image: alpine
        skipCheckout: true
        script: |
          echo "Hello, world!"
          echo "Pull request is created"
          echo "$CI_HEAD_REF -> $CI_BASE_REF"
      - name: pr-git
        image: alpine/git
        script: |
          echo "Current SHA of the git source is $(git rev-parse HEAD)"
        after:
          - pr-echo
    postSubmit:
      - name: push-echo
        image: alpine
        skipCheckout: true
        script: |
          echo "Hello, world!"
          echo "Code is pushed"
      - name: push-git
        image: alpine/git
        script: |
          echo "Current SHA of the git source is $(git rev-parse HEAD)"
        after:
          - push-echo
