apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: public-git-config
spec:
  git: # Configs for target repository
    type: github # Available : github, gitlab
    apiUrl: # url for self-served git servers (e.g. http://my.github). it is optional. 
    repository: tmax-cloud/cicd-sample-repo # pattern is {repo-owner}/{repo-name}
    token:
      valueFrom:
        secretKeyRef:
          name: git-token # FIY : 00-git-token.yaml 
          key: token # FIY : 00-git-token.yaml
  jobs:
    preSubmit:
    postSubmit:
