apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: job-using-tekton-task-config
spec:
  git:
    type: github
    apiUrl: 
    repository: tmax-cloud/cicd-sample-repo
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  jobs:
    preSubmit:
      - name: echo-using-tekton-task
        tektonTask: # You can use tekton tasks, rather than writing scripts in IntefarangionConfig
          taskRef:
            local: # available : local/catalog
              name: echo-hello-world
              kind: Task
