apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: build-and-push-image-using-secret-config
spec:
  git:
    type: github
    apiUrl: 
    repository: tmax-cloud/cicd-sample-repo
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  secrets: # you must create a secret to push your image to your desired image registry. (separate from git.token) Please refer to the comment below.
  - my-docker-hub-secret
  jobs:
    postSubmit:
      - name: build-and-push
        image: quay.io/buildah/stable
        script: |
          buildah bud --tls-verify=false --storage-driver=vfs --format docker -f ./Dockerfile -t $IMAGE_URL:${CI_HEAD_REF#refs/heads/} .
          buildah push --tls-verify=false --storage-driver=vfs $IMAGE_URL:${CI_HEAD_REF#refs/tags/} docker://$IMAGE_URL:${CI_HEAD_REF#refs/heads/}
        env:
          - name: IMAGE_URL
            value: yxzzzxh/repo # Use your docker registry
        securityContext:
          privileged: true
        when:
          branch:
            - main
# 
# you must create a secret to push your image to your desired image registry:
# e.g.) Create a secret named 'my-docker-hub-secret'
#
# kubectl create secret docker-registry my-docker-hub-secret \
#                    --docker-server=<your-registry-server> \
#                    --docker-username=<your-name> \
#                    --docker-password=<your-pword> \
#                    --docker-email=<your-email>
