apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  message : hello world
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  username: user
data:
  message: aGVsbG8gc2VjcmV0
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: workspaces-ref-configmap-secret-config
spec:
  git:
    type: github
    apiUrl: ""
    repository: tmax-cloud/cicd-sample-repo
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  workspaces:
    - name : workspace-for-configmap
      configMap:
        name: my-configmap
        items:
          - key: message
            path: my-message.txt
    - name : workspace-for-secret
      secret:
        secretName: my-secret
  jobs:
    preSubmit:
      - name: read-configmap
        image: ubuntu
        script: cat $(workspaces.workspace-for-configmap.path)/my-message.txt
      - name: read-secret
        image: ubuntu
        script:  |
          #!/usr/bin/env bash
          set -xe
          cat $(workspaces.workspace-for-secret.path)/username | grep "user"
          cat $(workspaces.workspace-for-secret.path)/message | grep "hello secret"
