apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-admin
subjects:
  - kind: ServiceAccount
    name: make-k8s-resource-and-role-binding-config-sa # IntegrationConfig creates ServiceAccount. "{Integration-name}-sa"
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-for-yaml
data:
  deployment-yaml : |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-deployment
      labels:
        app: test-deployment
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: test-deployment
      template:
        metadata:
          labels:
            app: test-deployment
        spec:
          containers:
            - name: test-deployment
              image: nginx:1.7.9
              ports:
              - containerPort: 80
---
apiVersion: cicd.tmax.io/v1
kind: IntegrationConfig
metadata:
  name: make-k8s-resource-and-role-binding-config
spec:
  git:
    type: github
    apiUrl: 
    repository: tmax-cloud/cicd-sample-repo
    token:
      valueFrom:
        secretKeyRef:
          name: git-token
          key: token
  workspaces:
    - name : workspace-for-yaml
      configMap:
        name: configmap-for-yaml
        items:
          - key: deployment-yaml
            path: deployment.yaml
  jobs:
    preSubmit:
      - name: run-kubectl-for-deploy
        image: lachlanevenson/k8s-kubectl
        command: ['kubectl']
        args:
          - 'apply'
          - '-f'
          - '$(workspaces.workspace-for-yaml.path)/deployment.yaml'
