apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: cicd-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-webhook
  namespace: cicd-system
  labels:
    cicd.tmax.io/part-of: controller
spec:
  rules:
    - host: waiting.for.loadbalancer
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: cicd-webhook
                port:
                  number: 24335
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-config
  namespace: cicd-system
  labels:
    cicd.tmax.io/part-of: controller
data:
  maxPipelineRun: "5"
  externalHostName: ""
  reportRedirectUriTemplate: ""
  enableMail: "false"
  smtpHost: ""
  smtpUserSecret: ""
  collectPeriod: "120"
  integrationJobTTL: "120"
  exposeMode: "Ingress"
  ingressClass: ""
  ingressHost: ""
  gitImage: "docker.io/alpine/git:1.0.30"
  gitCheckoutStepCPURequest: "30m"
  gitCheckoutStepMemRequest: "100Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-config
  namespace: cicd-system
  labels:
    cicd.tmax.io/part-of: controller
data:
  sizeS: '10'
  sizeM: '30'
  sizeL: '100'
  sizeXL: '500'
  sizeXXL: '1000'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-operator
  namespace: cicd-system
  labels:
    control-plane: controller-manager
    cicd.tmax.io/part-of: controller
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: cicd-service-account
      containers:
      - command:
        - /controller
        image: docker.io/tmaxcloudck/cicd-operator:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: EMAIL_TEMPLATE_PATH
            value: /templates/email
          - name: REPORT_TEMPLATE_PATH
            value: /templates/report
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /logs
            name: operator-log
          - name: email-template
            mountPath: /templates/email
          - name: report-template
            mountPath: /templates/report
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
        - name: operator-log
          hostPath:
            path: /var/log/cicd-operator/logs
        - name: email-template
          configMap:
            name: email-template
        - name: report-template
          configMap:
            name: report-template
      terminationGracePeriodSeconds: 10
