name: cicd-operator
on:
  push:
    branches:
      - master
      - v0.4.3
    tags:
      - v0.5.*
  pull_request:
    branches:
      - master
      - v0.4.3
jobs:
  test_crd:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: crd test
        run: make test-crd
  test_gen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: gen test
        run: make test-gen
  test_verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: verify test
        run: make test-verify
  test_unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: unit test
        run: make test-unit
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config .golangci.yaml
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v0.5')
    needs: [test_gen, test_verify, test_unit, test_lint, test_crd]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: build
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}

          REPO_OPERATOR=tmaxcloudck/cicd-operator
          REPO_BLOCKER=tmaxcloudck/cicd-blocker
          REPO_WEBHOOK=tmaxcloudck/cicd-webhook
          REPO_APISERVER=tmaxcloudck/cicd-api-server

          IMG_OPERATOR=${REPO_OPERATOR}:${GITHUB_REF#refs/tags/}
          IMG_BLOCKER=${REPO_BLOCKER}:${GITHUB_REF#refs/tags/}
          IMG_WEBHOOK=${REPO_WEBHOOK}:${GITHUB_REF#refs/tags/}
          IMG_APISERVER=${REPO_APISERVER}:${GITHUB_REF#refs/tags/}

          docker build . -t ${IMG_OPERATOR} -f build/controller/Dockerfile
          docker build . -t ${IMG_BLOCKER} -f build/blocker/Dockerfile
          docker build . -t ${IMG_WEBHOOK} -f build/webhook/Dockerfile
          docker build . -t ${IMG_APISERVER} -f build/apiserver/Dockerfile
          docker tag ${IMG_OPERATOR} ${REPO_OPERATOR}:latest
          docker tag ${IMG_BLOCKER} ${REPO_BLOCKER}:latest
          docker tag ${IMG_WEBHOOK} ${REPO_WEBHOOK}:latest
          docker tag ${IMG_APISERVER} ${REPO_APISERVER}:latest
          docker push ${IMG_OPERATOR}
          docker push ${IMG_BLOCKER}
          docker push ${IMG_WEBHOOK}
          docker push ${IMG_APISERVER}
          docker push ${REPO_OPERATOR}:latest
          docker push ${REPO_BLOCKER}:latest
          docker push ${REPO_WEBHOOK}:latest
          docker push ${REPO_APISERVER}:latest
