name: cicd-operator
on:
  push:
    branches:
      - v0.4.2-release2
    tags:
      - v0.4.2-*
  pull_request:
    branches:
      - v0.4.2-release2
jobs:
  test_crd:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: crd test
        run: make test-crd
  test_gen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: gen test
        run: make test-gen
  test_verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: verify test
        run: make test-verify
  test_unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: unit test
        run: make test-unit
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2.2.1
        with:
          version: v1.29
          args: -v -E gofmt -E golint -E gocyclo -E misspell --timeout 1h0m0s
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v0.4.2-')
    needs: [test_gen, test_verify, test_unit, test_lint, test_crd]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}

          REPO_OPERATOR=tmaxcloudck/cicd-operator
          REPO_BLOCKER=tmaxcloudck/cicd-blocker

          IMG_OPERATOR=${REPO_OPERATOR}:${GITHUB_REF#refs/tags/}
          IMG_BLOCKER=${REPO_BLOCKER}:${GITHUB_REF#refs/tags/}

          docker build . -t ${IMG_OPERATOR} -f build/controller/Dockerfile
          docker build . -t ${IMG_BLOCKER} -f build/blocker/Dockerfile
          docker push ${IMG_OPERATOR}
          docker push ${IMG_BLOCKER}
