name: cicd-operator
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  test_gen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gen test
        run: make test-gen
  test_verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: verify test
        run: make test-verify
  test_unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: unit test
        run: make test-unit
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
          args: -v -E gofmt --timeout 1h0m0s
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test_gen, test_verify, test_unit, test_lint]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}
          make build push push-latest VERSION=${GITHUB_REF#refs/tags/}
